# Generated by Django 3.1.1 on 2020-09-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20200917_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailentry',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
