# Generated by Django 3.1.1 on 2020-12-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredpost',
            name='url',
            field=models.CharField(default='none', max_length=200, unique=True),
        ),
    ]
